name: CI-DI-Pipeline-to-AWS-ECS
env: 
  AWS_REGION_NAME:             "us-east-1" 
  ECR_REPO_NAME:               "tender_notify"
  
on:
  push:
    branches: [ main ]
    
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
         aws-access-key-id: ${{secrets.MY_AWS_ACCESS_KEY}}
         aws-secret-access-key: ${{secrets.MY_AWS_SECRET_KEY}}
         aws-region: ${{env.AWS_REGION_NAME}}
        
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${{env.AWS_REGION_NAME}} | docker login --username AWS --password-stdin 948206608465.dkr.ecr.us-east-1.amazonaws.com
        
      - name: Create Docker image
        run: docker build -t ${{env.ECR_REPO_NAME}} .
        
      - name: Rename Docker image for AWS
        run: docker tag ${{env.ECR_REPO_NAME}}:latest 948206608465.dkr.ecr.us-east-1.amazonaws.com/${{env.ECR_REPO_NAME}}:latest
        
      - name: Push Docker image to AWS ECR
        run: docker push 948206608465.dkr.ecr.us-east-1.amazonaws.com/${{env.ECR_REPO_NAME}}:latest
        
      - name: Render AWS ECS task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-notify-container
        with: 
           task-definition: task-definition.json
           container-name: notify
           image: 948206608465.dkr.ecr.us-east-1.amazonaws.com/${{env.ECR_REPO_NAME}}:latest
           
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
           task-definition: ${{ steps.render-web-container.outputs.task-definition }}
           cluster: tenders
        
  
