name: CI-DI-Pipeline-to-AWS-ElasticBeanstalk
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "ttm-test-app-packages"
  EB_APPLICATION_NAME :        "ZakupkiNotificator"
  EB_ENVIROMENT_NAME:          "zakupki-env"
  DEPLOY_PACKAGE_NAME:         "ttmje/zakupkinotificator"  # "zakupkiNotificator_${{github.sha}}"
  AWS_REGION_NAME:             "us-east-1"
  ECR_REPO_NAME:               "tender_notify"
  
on:
  push:
    branches: [ main ]
    
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2
        
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${{env.AWS_REGION_NAME}} | docker login --username${{secrets.AWS_LOGIN}} --password${{secrets.AWS_PASSWORD}} 948206608465.dkr.ecr.us-east-1.amazonaws.com
        
      - name: Create Docker image
        run: docker build -t ${{env.ECR_REPO_NAME}} .
        
      - name: Rename Docker image for AWS
        run: docker tag ${{env.ECR_REPO_NAME}}:latest 948206608465.dkr.ecr.us-east-1.amazonaws.com/${{env.ECR_REPO_NAME}}:latest
        
      - name: Push Docker image to AWS ECR
        run: docker push 948206608465.dkr.ecr.us-east-1.amazonaws.com/${{env.ECR_REPO_NAME}}:latest
        
  
